server:
  port: 8080
spring:
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
  type: com.alibaba.druid.pool.DruidDataSource


 redis:
  host: 127.0.0.1
  port: 6379
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  servlet:
   content-type: text/html
  mode: HTML5
  cache: false

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: Mapper/*Mapper.xml
shiro:
 loginUrl: /tologin
 successUrl: /


